#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_GOOGLE_include_directive : enable

layout(binding=0) uniform accelerationStructureEXT TLAS;
layout(binding=1, rgba32f) uniform image2D image;

#include "raycommon.glsli"

layout(location=0) rayPayloadEXT hitPayload payload;

void main() {
  const vec2 uv = (vec2(gl_LaunchIDEXT.xy) + vec2(0.5)) / vec2(gl_LaunchSizeEXT.xy);

  vec3 origin = vec3(uv * 2.0 - 1.0, -1.0);
  origin.y *= -1;
  vec3 dir = vec3(0, 0, 1);
  uint rayFlags = gl_RayFlagsNoneEXT;
  float tMin = 0.01f;
  float tMax = 10000.0f;

  payload.hitValue = vec3(uv, 1.0);

  traceRayEXT(TLAS,
              rayFlags,
              0xFF,
              0,
              0,
              0,
              origin,
              tMin,
              dir,
              tMax,
              0
  );

  imageStore(image, ivec2(gl_LaunchIDEXT.xy), vec4(payload.hitValue, 1.0));
}