#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_GOOGLE_include_directive : enable

#include "raycommon.glsli"

layout(binding=0) uniform accelerationStructureEXT TLAS;
layout(binding=1, rgba32f) uniform image2D image;
layout(binding=2) uniform RtPerSceneData {
    mat4 InverseView;
    mat4 InverseProj;
};

layout(location=0) rayPayloadEXT hitPayload payload;

void main() {
  const vec2 uv = (vec2(gl_LaunchIDEXT.xy) + vec2(0.5)) / vec2(gl_LaunchSizeEXT.xy);
  imageStore(image, ivec2(gl_LaunchIDEXT.xy), vec4(uv, 1.0, 1.0));
}