#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_debug_printf : enable

#include "raycommon.glsl"

layout(binding=1, rgba32f) uniform image2D image;
layout(binding=0) uniform accelerationStructureEXT TLAS;
layout(location=0) rayPayloadEXT hitPayload payload;

void main() {
  const vec2 uv = (vec2(gl_LaunchIDEXT.xy) + vec2(0.5)) / vec2(gl_LaunchSizeEXT.xy);
  vec3 origin = vec3(uv.x * 2.0 - 1.0, uv.y * 2.0 - 1.0, 1.0);
  vec3 dir = vec3(0, 0, -1);

  traceRayEXT(TLAS,
    gl_RayFlagsNoneEXT,
    0xFF,    // Instance inclusion mask
    0,       // SBT record offset
    0,       // SBT record stride for offset
    0,       // Miss index
    origin,  // Ray origin
    0.0,     // Minimum t-value
    dir ,    // Ray direction
    1000.0 , // Maximum t-value
    0        // Location of payload
  );

  imageStore(image, ivec2(gl_LaunchIDEXT.xy), vec4(payload.hitValue, 1.0));
}