#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_GOOGLE_include_directive : enable

#include "raycommon.glsli"

layout(location=0) rayPayloadInEXT hitPayload prd;
hitAttributeEXT vec2 attribs;

layout(binding=3) uniform sampler2D texSampler1;

struct Vertex {
	vec2 pos;
	vec3 color;
	vec2 uv;
};
layout(std430, binding=4) readonly buffer VertexBuf {
	Vertex vertices[];
};

layout(std430, binding=5) readonly buffer IndexBuf {
    uint indices[];
};

void main() {
  // read UV
  uint idx0 = indices[gl_PrimitiveID * 3];
  uint idx1 = indices[gl_PrimitiveID * 3 + 1];
  uint idx2 = indices[gl_PrimitiveID * 3 + 2];
  vec2 uv0 = vertices[idx0].uv;
  vec2 uv1 = vertices[idx1].uv;
  vec2 uv2 = vertices[idx2].uv;
  
  const vec3 bary = vec3(1.0 - attribs.x - attribs.y, attribs.x, attribs.y);
  const vec2 uv = uv0 * bary.x + uv1 * bary.y + uv2 * bary.z;
  prd.hitValue = vec3(uv, 0);
  vec3 t = texture(texSampler1, uv).xyz;
  if (t.x < 0.5) {
    ignoreIntersectionEXT;
  } else {
  }
}